[package]
name = "grepq"
version = "1.3.5"
edition = "2021"
authors = ["Nicholas D. Crosbie"]
license = "MIT"
description = "quickly filter fastq files"
homepage = "https://github.com/Rbfinch/grepq"
documentation = "https://github.com/Rbfinch/grepq"
repository = "https://github.com/Rbfinch/grepq"
readme = "README.md"
categories = ["science"]
keywords = ["bioinformatics", "FASTQ", "REGEX", "JSON", "cli"]

[dependencies]
seq_io = "0.3.2"
regex = "1.11.1"
mimalloc = "0.1.43"
clap = { version = "4.5.23", features = ["derive", "cargo"] }
num_cpus = "1.16.0"
flate2 = "1.0.35"
jsonschema = "0.28.0"
serde_json = "1.0.134"
env_logger = "0.11.6"
log = "0.4.22"
colored = "2.2.0"

[profile.release]
lto = true