[package]
name = "grepq"
version = "1.5.4"
edition = "2021"
authors = ["Nicholas D. Crosbie"]
license = "MIT"
description = "quickly filter fastq files"
homepage = "https://github.com/Rbfinch/grepq"
documentation = "https://github.com/Rbfinch/grepq"
repository = "https://github.com/Rbfinch/grepq"
readme = "README.md"
categories = ["science"]
keywords = ["bioinformatics", "FASTQ", "REGEX", "JSON", "cli"]

[dependencies]
seq_io = "0.3.4"
regex = "1.11.1"
mimalloc = "0.1.44"
clap = { version = "4.5.32", features = ["derive", "cargo"] }
num_cpus = "1.16.0"
flate2 = { version = "1.1.0", features = ["zlib-ng"], default-features = false }
jsonschema = "0.29.0"
serde_json = "1.0.140"
colored = "3.0.0"
zstd = "0.13.3"
rusqlite = "0.34.0"
chrono = "0.4.40"
serde = "1.0.219"
clap-markdown = "0.1.4"

[dev-dependencies]
tempfile = "3.19.1"
criterion = { version = "0.5.1", features = ["html_reports"] }

[lib]
name = "grepq"
path = "src/lib.rs"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
lto = true
