[package]
name = "grepq"
version = "1.1.8"
edition = "2021"
authors = ["Nicholas D. Crosbie"]
license = "MIT"
description = "quickly filter fastq files by matching sequences to a set of regex patterns"
homepage = "https://github.com/Rbfinch/grepq"
documentation = "https://github.com/Rbfinch/grepq"
repository = "https://github.com/Rbfinch/grepq"
readme = "README.md"
categories = ["science"]
keywords = ["bioinformatics", "fastq"]

[dependencies]
seq_io = "0.3.2"
regex = "1.11.1"
mimalloc = "0.1.43"
clap = { version = "4.5.20", features = ["derive", "cargo"] }
num_cpus = "1.16.0"
flate2 = "1.0.35"

[profile.release]
lto = true
